package com.ithaque.funnies.funnies;

import org.junit.Before;
import org.junit.Test;

import com.ithaque.funnies.basic.AbstractTestCase;
import com.ithaque.funnies.shared.basic.Location;
import com.ithaque.funnies.shared.funny.boardgame.CounterFunny;
import com.ithaque.funnies.shared.funny.boardgame.GameBoardCircus;
import com.ithaque.funnies.shared.funny.boardgame.TileFunny;
import com.ithaque.funnies.shared.funny.manager.AbstractCircusManager;

public class TestCircus extends AbstractTestCase {

	GameBoardCircus gbc;
	AbstractCircusManager circusManager;
	CounterFunny counter;
	TileFunny tile;
	
	@Before
	public void setup() {
		gbc = new GameBoardCircus(platform, 1000.0f, 500.0f);
		circusManager = new AbstractCircusManager() {
		};
		gbc.init(circusManager);
	}
	
	@Test
	public void testLaunchSimpleCircus() {
		process(0);
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].getCoordinateSpaceWidth()");
		expect("Canvas[0].getCoordinateSpaceHeight()");
		expect("Canvas[0].setVisible(true)");
		expect("Canvas[1].setVisible(false)");
		expect("Canvas[1].restoreContext2D()");
		expect("Canvas[1].saveContext2D()");
		expect("Context2D[1].beginPath()");
		expect("Canvas[1].getCoordinateSpaceWidth()");
		expect("Canvas[1].getCoordinateSpaceHeight()");
		expect("Context2D[1].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[2].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[2].setVisible(true)");
		expect("Canvas[2].setCoordinateSpaceWidth(1000)");
		expect("Canvas[2].setCoordinateSpaceHeight(500)");
		expect("Canvas[2].saveContext2D()");
		expect("Canvas[2].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[3].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[3].setVisible(false)");
		expect("Canvas[3].setCoordinateSpaceWidth(1000)");
		expect("Canvas[3].setCoordinateSpaceHeight(500)");
		expect("Canvas[3].saveContext2D()");
		expect("Canvas[3].addToRootPanel()");
		expect("Canvas[2].setVisible(true)");
		expect("Canvas[3].setVisible(false)");
		expect("Canvas[3].restoreContext2D()");
		expect("Canvas[3].saveContext2D()");
		expect("Context2D[3].beginPath()");
		expect("Canvas[3].getCoordinateSpaceWidth()");
		expect("Canvas[3].getCoordinateSpaceHeight()");
		expect("Context2D[3].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[4].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[4].setVisible(true)");
		expect("Canvas[4].setCoordinateSpaceWidth(1000)");
		expect("Canvas[4].setCoordinateSpaceHeight(500)");
		expect("Canvas[4].saveContext2D()");
		expect("Canvas[4].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[5].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[5].setVisible(false)");
		expect("Canvas[5].setCoordinateSpaceWidth(1000)");
		expect("Canvas[5].setCoordinateSpaceHeight(500)");
		expect("Canvas[5].saveContext2D()");
		expect("Canvas[5].addToRootPanel()");
		expect("Canvas[4].setVisible(true)");
		expect("Canvas[5].setVisible(false)");
		expect("Canvas[5].restoreContext2D()");
		expect("Canvas[5].saveContext2D()");
		expect("Context2D[5].beginPath()");
		expect("Canvas[5].getCoordinateSpaceWidth()");
		expect("Canvas[5].getCoordinateSpaceHeight()");
		expect("Context2D[5].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[6].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[6].setVisible(true)");
		expect("Canvas[6].setCoordinateSpaceWidth(1000)");
		expect("Canvas[6].setCoordinateSpaceHeight(500)");
		expect("Canvas[6].saveContext2D()");
		expect("Canvas[6].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[7].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[7].setVisible(false)");
		expect("Canvas[7].setCoordinateSpaceWidth(1000)");
		expect("Canvas[7].setCoordinateSpaceHeight(500)");
		expect("Canvas[7].saveContext2D()");
		expect("Canvas[7].addToRootPanel()");
		expect("Canvas[6].setVisible(true)");
		expect("Canvas[7].setVisible(false)");
		expect("Canvas[7].restoreContext2D()");
		expect("Canvas[7].saveContext2D()");
		expect("Context2D[7].beginPath()");
		expect("Canvas[7].getCoordinateSpaceWidth()");
		expect("Canvas[7].getCoordinateSpaceHeight()");
		expect("Context2D[7].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[8].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[8].setVisible(true)");
		expect("Canvas[8].setCoordinateSpaceWidth(1000)");
		expect("Canvas[8].setCoordinateSpaceHeight(500)");
		expect("Canvas[8].saveContext2D()");
		expect("Canvas[8].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[9].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[9].setVisible(false)");
		expect("Canvas[9].setCoordinateSpaceWidth(1000)");
		expect("Canvas[9].setCoordinateSpaceHeight(500)");
		expect("Canvas[9].saveContext2D()");
		expect("Canvas[9].addToRootPanel()");
		expect("Canvas[8].setVisible(true)");
		expect("Canvas[9].setVisible(false)");
		expect("Canvas[9].restoreContext2D()");
		expect("Canvas[9].saveContext2D()");
		expect("Context2D[9].beginPath()");
		expect("Canvas[9].getCoordinateSpaceWidth()");
		expect("Canvas[9].getCoordinateSpaceHeight()");
		expect("Context2D[9].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[10].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[10].setVisible(true)");
		expect("Canvas[10].setCoordinateSpaceWidth(1000)");
		expect("Canvas[10].setCoordinateSpaceHeight(500)");
		expect("Canvas[10].saveContext2D()");
		expect("Canvas[10].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[11].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[11].setVisible(false)");
		expect("Canvas[11].setCoordinateSpaceWidth(1000)");
		expect("Canvas[11].setCoordinateSpaceHeight(500)");
		expect("Canvas[11].saveContext2D()");
		expect("Canvas[11].addToRootPanel()");
		expect("Canvas[10].setVisible(true)");
		expect("Canvas[11].setVisible(false)");
		expect("Canvas[11].restoreContext2D()");
		expect("Canvas[11].saveContext2D()");
		expect("Context2D[11].beginPath()");
		expect("Canvas[11].getCoordinateSpaceWidth()");
		expect("Canvas[11].getCoordinateSpaceHeight()");
		expect("Context2D[11].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[12].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[12].setVisible(true)");
		expect("Canvas[12].setCoordinateSpaceWidth(1000)");
		expect("Canvas[12].setCoordinateSpaceHeight(500)");
		expect("Canvas[12].saveContext2D()");
		expect("Canvas[12].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[13].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[13].setVisible(false)");
		expect("Canvas[13].setCoordinateSpaceWidth(1000)");
		expect("Canvas[13].setCoordinateSpaceHeight(500)");
		expect("Canvas[13].saveContext2D()");
		expect("Canvas[13].addToRootPanel()");
		expect("Canvas[12].setVisible(true)");
		expect("Canvas[13].setVisible(false)");
		expect("Canvas[13].restoreContext2D()");
		expect("Canvas[13].saveContext2D()");
		expect("Context2D[13].beginPath()");
		expect("Canvas[13].getCoordinateSpaceWidth()");
		expect("Canvas[13].getCoordinateSpaceHeight()");
		expect("Context2D[13].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[14].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[14].setVisible(true)");
		expect("Canvas[14].setCoordinateSpaceWidth(1000)");
		expect("Canvas[14].setCoordinateSpaceHeight(500)");
		expect("Canvas[14].saveContext2D()");
		expect("Canvas[14].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[15].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[15].setVisible(false)");
		expect("Canvas[15].setCoordinateSpaceWidth(1000)");
		expect("Canvas[15].setCoordinateSpaceHeight(500)");
		expect("Canvas[15].saveContext2D()");
		expect("Canvas[15].addToRootPanel()");
		expect("Canvas[14].setVisible(true)");
		expect("Canvas[15].setVisible(false)");
		expect("Canvas[15].restoreContext2D()");
		expect("Canvas[15].saveContext2D()");
		expect("Context2D[15].beginPath()");
		expect("Canvas[15].getCoordinateSpaceWidth()");
		expect("Canvas[15].getCoordinateSpaceHeight()");
		expect("Context2D[15].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[16].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[16].setVisible(true)");
		expect("Canvas[16].setCoordinateSpaceWidth(1000)");
		expect("Canvas[16].setCoordinateSpaceHeight(500)");
		expect("Canvas[16].saveContext2D()");
		expect("Canvas[16].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[17].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[17].setVisible(false)");
		expect("Canvas[17].setCoordinateSpaceWidth(1000)");
		expect("Canvas[17].setCoordinateSpaceHeight(500)");
		expect("Canvas[17].saveContext2D()");
		expect("Canvas[17].addToRootPanel()");
		expect("Canvas[16].setVisible(true)");
		expect("Canvas[17].setVisible(false)");
		expect("Canvas[17].restoreContext2D()");
		expect("Canvas[17].saveContext2D()");
		expect("Context2D[17].beginPath()");
		expect("Canvas[17].getCoordinateSpaceWidth()");
		expect("Canvas[17].getCoordinateSpaceHeight()");
		expect("Context2D[17].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[18].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[18].setVisible(true)");
		expect("Canvas[18].setCoordinateSpaceWidth(1000)");
		expect("Canvas[18].setCoordinateSpaceHeight(500)");
		expect("Canvas[18].saveContext2D()");
		expect("Canvas[18].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[19].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[19].setVisible(false)");
		expect("Canvas[19].setCoordinateSpaceWidth(1000)");
		expect("Canvas[19].setCoordinateSpaceHeight(500)");
		expect("Canvas[19].saveContext2D()");
		expect("Canvas[19].addToRootPanel()");
		expect("Canvas[18].setVisible(true)");
		expect("Canvas[19].setVisible(false)");
		expect("Canvas[19].restoreContext2D()");
		expect("Canvas[19].saveContext2D()");
		expect("Context2D[19].beginPath()");
		expect("Canvas[19].getCoordinateSpaceWidth()");
		expect("Canvas[19].getCoordinateSpaceHeight()");
		expect("Context2D[19].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Platform[0].createCanvas()");
		expect("Canvas[20].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[20].setVisible(true)");
		expect("Canvas[20].setCoordinateSpaceWidth(1000)");
		expect("Canvas[20].setCoordinateSpaceHeight(500)");
		expect("Canvas[20].saveContext2D()");
		expect("Canvas[20].addToRootPanel()");
		expect("Platform[0].createCanvas()");
		expect("Canvas[21].setAttribute(position:absolute;left:0px;top:0px;)");
		expect("Canvas[21].setVisible(false)");
		expect("Canvas[21].setCoordinateSpaceWidth(1000)");
		expect("Canvas[21].setCoordinateSpaceHeight(500)");
		expect("Canvas[21].saveContext2D()");
		expect("Canvas[21].addToRootPanel()");
		expect("Canvas[20].setVisible(true)");
		expect("Canvas[21].setVisible(false)");
		expect("Canvas[21].restoreContext2D()");
		expect("Canvas[21].saveContext2D()");
		expect("Context2D[21].beginPath()");
		expect("Canvas[21].getCoordinateSpaceWidth()");
		expect("Canvas[21].getCoordinateSpaceHeight()");
		expect("Context2D[21].clearRect(0.0, 0.0, 1000.0, 500.0)");
		expect("Canvas[2].setVisible(false)");
		expect("Canvas[3].setVisible(true)");
		expect("Canvas[4].setVisible(false)");
		expect("Canvas[5].setVisible(true)");
		expect("Canvas[6].setVisible(false)");
		expect("Canvas[7].setVisible(true)");
		expect("Canvas[8].setVisible(false)");
		expect("Canvas[9].setVisible(true)");
		expect("Canvas[10].setVisible(false)");
		expect("Canvas[11].setVisible(true)");
		expect("Canvas[12].setVisible(false)");
		expect("Canvas[13].setVisible(true)");
		expect("Canvas[14].setVisible(false)");
		expect("Canvas[15].setVisible(true)");
		expect("Canvas[16].setVisible(false)");
		expect("Canvas[17].setVisible(true)");
		expect("Canvas[18].setVisible(false)");
		expect("Canvas[19].setVisible(true)");
		expect("Canvas[20].setVisible(false)");
		expect("Canvas[21].setVisible(true)");
		expect("Canvas[0].setVisible(false)");
		expect("Canvas[1].setVisible(true)");
		nothingExpected();
	}
	
	@Test
	public void testAddACounter() {
		process(0);
		counter = new CounterFunny("c0", "u1.png");
		counter.setLocation(new Location(-100, 0));
		gbc.enterRing(counter);
		process(40);
		find("Platform[0].createImage(u1.png)");
		expect("Image[u1.png].Image()");
		load("u1.png", 70, 70);
		process(80);
		find("Context2D[11].setTransform(1.0, 0.0, 0.0, 1.0, 400.0, 250.0)");
		expect("Context2D[11].setGlobalAlpha(1.0)");
		expect("Context2D[11].translate(-35.0, -35.0)");
		expect("Context2D[11].drawImage(u1.png, 0, 0, 70, 70, 0, 0, 70, 70)");
	}

	@Test
	public void testAddATile() {
		process(0);
		tile = new TileFunny.HHexFunny("t0", "hexagon.png", "hhexagon.png", "rhexagon.png", 26.0f, 100, -200);
		gbc.enterRing(tile);
		process(40);
		find("Platform[0].createImage(hexagon.png)");
		find("Platform[0].createImage(hhexagon.png)");
		find("Platform[0].createImage(rhexagon.png)");
		load("hexagon.png", 70, 70);
		load("hhexagon.png", 70, 70);
		load("rhexagon.png", 70, 70);
		process(80);
		find("Context2D[5].setTransform(1.0, 0.0, 0.0, 1.0, 600.0, 50.0)");
		expect("Context2D[5].setGlobalAlpha(1.0)");
		expect("Context2D[5].translate(-35.0, -35.0)");
		expect("Context2D[5].drawImage(hexagon.png, 0, 0, 70, 70, 0, 0, 70, 70)");
	}
}
